theme: jekyll-theme-minimal

title: Piero Cavalcanti
logo: assets/images/datascientist.JPG
description: Let's talk about data. And movies. And books. And stuff.
show_downloads: false
google_analytics:
